name: CI
on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
env:
  NODE_VERSION: '17'
jobs:
  npm-check-updates:
    if: startsWith(github.event.inputs.trigger, 'm')
      || startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
      - run: export SET NODE_OPTIONS=--openssl-legacy-provider && npx npm-check-updates
  docs:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm i -E
      #- run: export SET NODE_OPTIONS=--openssl-legacy-provider && npm run github-pages
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run github-pages
      - name: GitHub Pages Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: src/.vuepress/dist # The folder the action should deploy.
